<?php 
	
	mysqli_connect('localhost','root','1') or die('could not connected to the database');
	mysqli_connect('localhost','root','1');
	die('could not connected to the database');
	echo "connected";

// The @ symbol is the error control operator (aka the "silence" or "shut-up" operator). 
// It makes PHP suppress any error messages (notice, warning, fatal, etc) generated by the associated expression. 
// It works just like a unary operator, for example, it has a precedence and associativity.